---
kind: pipeline
type: kubernetes
name: rtp-test-lib

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:latest
  commands:
  - . /root/entrypoint.sh
  - git fetch --tags
  - sbt clean coverage test coverageReport coverageOff
  - sbt dependencyCheck
  - sbt scalastyle
  - sbt scapegoat
  - sbt clean test
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: regt-build-bot
    JRE_VERSION: 21
    OVERRIDE_BUILD_REPOS: "false"
  when:
    event:
    - push
    - tag

- name: publish
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:latest
  commands:
  - /root/entrypoint.sh
  - sbt clean +publish
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_SERVER: https://artifactory.digital.homeoffice.gov.uk/
    ARTIFACTORY_USERNAME: regt-build-bot
    JRE_VERSION: 17
  when:
    branch:
    - master
    event:
    - push
    - tag
  depends_on:
    - build

...
