---
kind: pipeline
type: kubernetes
name: rtp-test-lib

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt:latest
  commands:
  - rm /app/.sbt/repositories
  - echo -en "[repositories]\n  local\n  lib-releases: https://artifactory.digital.homeoffice.gov.uk/artifactory/libs-release/\n  lib-snapshots: https://artifactory.digital.homeoffice.gov.uk/artifactory/libs-snapshot/\n" > /app/.sbt/repositories
  - . /app/entrypoint.sh
  - git fetch --tags
  - sbt clean coverage test coverageReport coverageOff
  - sbt dependencyCheck
  - sbt scalastyle
  - sbt scapegoat
  - sbt clean test
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: regt-build-bot
    JRE_VERSION: 21
    OVERRIDE_BUILD_REPOS: "false"
  when:
    event:
    - push
    - tag

- name: sonar-scanner
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner:v4.6
  commands:
  - sonar-scanner
  when:
    event:
    - push
    - tag
  depends_on:
    - build

- name: publish
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt:latest
  commands:
  - rm /app/.sbt/repositories
  - . /app/entrypoint.sh
  - sbt clean +publish
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: regt-build-bot
    OVERRIDE_BUILD_REPOS: "false"
    JRE_VERSION: 21
  when:
    branch:
    - master
    event:
    - push
    - tag
  depends_on:
    - sonar-scanner

...
